### ISSUE TITLE
How to hide tooltip after a button is pressed?

### ISSUE THREAD

**Issue by emaillenin** [ghosh/microtip#41]
Not sure if this is a bug or expected behaviour. When we only hover the button, the tooltip disappears after the mouse is moved away. But when the button is clicked and then moved away, the tooltip stays, how can we remove the tooltip after the click?

Reproduced no https://microtip.now.sh/

![tooltip-bug-microtip](https://user-images.githubusercontent.com/1235853/77821175-1be9a800-710e-11ea-84fa-864c893a4aa0.gif)

**Comment by ghosh** [comment]
Thanks for reporting @emaillenin. This behaviour is only affecting `<a />` tags. Seems like the button and other elements are fine.

I am unsure what's causing this. Will investigate.

**Comment by Muhnad** [comment]
Hey @ghosh & @emaillenin 

it's not a bug it the default state for focus elements like button, link(a) etc.... 

let's talk about CSS states:
1. [hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover): when you hover the button the tooltip disappears after the mouse is moved out. its the default state for hover. the action happens while you hovering on it.

2. [focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus): when you focus on the button the tooltip will appear until you de-focus the button or focus to another focusable element.

3. [active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active): when you click on the button you trigger the active state and active state trigger focus state so the tooltip will appear until you de-focus the button.........


try to click on any button on the [example](https://codepen.io/Muhnad/pen/BaoZgKL) and you will see the button is triggered focus state.

<img width="311" alt="Screen Shot 2020-04-29 at 2 14 52 AM" src="https://user-images.githubusercontent.com/13405108/80550101-3d64da80-89bf-11ea-8ca0-da76ecf19053.png">

**Comment by ghosh** [comment]
Thanks for the breakdown @Muhnad, I see your point.

If that’s the case then we should leave the behaviour as is right? No need to make any changes for now?

**Comment by Muhnad** [comment]
Exactly yeah. We don't need to any changes. It work as expected.
