### ISSUE TITLE
does not support ie 11

### ISSUE THREAD

**Issue by richiemaen** [ghosh/microtip#44]
Microtip data-microtip-position="top" data-microtip-size="large"  is working in chrome but not in ie11

**Comment by ghosh** [comment]
Please see https://github.com/ghosh/microtip/issues/36

**Comment by richiemaen** [comment]
not working on my end. already tried #36 @ghosh

**Comment by ghosh** [comment]
Noted. Will address this in the next release.

**Comment by richiemaen** [comment]
thanks @ghosh  your plugin is really helpful
